"""Hardwax scraper.

Hardwax (hardwax.com) is the Berlin techno / dub-techno reference shop.
The current template uses minified CSS class names (`ps`, `qz`, `rl`, etc.)
generated by a build step, so semantic class selectors are unstable. What is
stable:

1. Every record card is `<div id="record-NNNNN">` (numeric ID, `record-` prefix).
2. Each card contains a cover-image anchor `<a class="an" href="/{id}/{artist}/{title}/">`.
   That URL path is the cleanest source of artist + title — the slugs survive
   any CSS reshuffle.

So the parser is URL-driven, not selector-driven: find each `div[id^="record-"]`,
read its `a.an` href, parse `(record_id, artist_slug, title_slug)` from the
path, and convert slugs to display form. Fail-soft on DOM drift, dump a
diagnostic on a no-cards run.
"""
from __future__ import annotations

import logging
from urllib.parse import urljoin

from selectolax.parser import HTMLParser, Node

from agent.config import settings
from agent.sources._debug import log_no_cards_diagnostic
from agent.sources._http import IMPERSONATE, AsyncSession
from agent.sources.rss import RawRelease

logger = logging.getLogger("cratedigger-agent.sources.hardwax")

BASE_URL = "https://hardwax.com"
INDEX_PATH = "/this-week/"

# div[id^="record-"] is the canonical card. Fallbacks in case Hardwax ever
# moves to a different ID scheme — historically they've used <li class="record">.
_CARD_SELECTORS = (
    'div[id^="record-"]',
    "li.record",
    "article.record",
    "div.record",
)


def _slug_to_display(slug: str) -> str:
    """Convert a URL slug like 'mary-yuzovskaya' to 'Mary Yuzovskaya'.

    Hardwax slugs are lowercased and hyphen-separated. We naive-titlecase per
    word; catalog-number-style slugs like 'bin008' come back as 'Bin008',
    which is harmless — the metadata-fetch step downstream can normalize.
    """
    if not slug:
        return ""
    return " ".join(word.capitalize() for word in slug.split("-"))


def _parse_card(card: Node) -> RawRelease | None:
    # The cover-image anchor's href encodes both artist and title as URL slugs.
    anchor = card.css_first("a.an") or card.css_first("a[href]")
    if anchor is None:
        return None
    href = anchor.attributes.get("href") or ""

    parts = [p for p in href.split("/") if p]
    # Expected path: /<record_id>/<artist-slug>/<title-slug>/  → 3 parts
    if len(parts) < 3:
        return None
    record_id, artist_slug, title_slug = parts[0], parts[1], parts[2]
    if not record_id.isdigit():
        return None

    artist = _slug_to_display(artist_slug)
    title = _slug_to_display(title_slug)
    if not artist and not title:
        return None

    cover_img = card.css_first("img.aj") or card.css_first("img")
    cover = cover_img.attributes.get("src") if cover_img is not None else None

    return RawRelease(
        title=title,
        artist=artist,
        label=None,
        catalog_number=None,
        release_date=None,
        url=urljoin(BASE_URL, href),
        cover_art_url=cover,
        description=f"{artist} — {title}",
        source_slug="hardwax",
    )


async def scrape_hardwax() -> list[RawRelease]:
    """Scrape Hardwax's this-week listing. Returns RawReleases."""
    headers = {"User-Agent": settings.crawler_user_agent}
    try:
        async with AsyncSession(
            timeout=20.0, headers=headers, impersonate=IMPERSONATE
        ) as http:
            resp = await http.get(BASE_URL + INDEX_PATH, allow_redirects=True)
            resp.raise_for_status()
            html = resp.text
    except Exception as e:
        logger.error("Hardwax fetch failed: %s", e)
        return []

    tree = HTMLParser(html)
    cards: list[Node] = []
    for sel in _CARD_SELECTORS:
        cards = tree.css(sel)
        if cards:
            logger.info("Hardwax: %d cards via selector %r", len(cards), sel)
            break

    if not cards:
        log_no_cards_diagnostic(logger, "hardwax", html)
        return []

    out: list[RawRelease] = []
    for card in cards:
        try:
            release = _parse_card(card)
        except Exception as e:
            logger.warning("Hardwax card parse error: %s", e)
            continue
        if release is not None:
            out.append(release)

    logger.info("Hardwax: parsed %d releases", len(out))
    return out
