services:
  db:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cratedigger
      POSTGRES_PASSWORD: cratedigger
      POSTGRES_DB: cratediggerdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./packages/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
