"""Database pool + idempotent migration runner.

Pattern harvested from Sift's `app/db.py`. The pool wrapper (init/get/close)
is verbatim. The `_apply_migrations()` body is rewritten — Sift's migrations
are news-domain (story_threading, why_it_matters, outlet_profiles, civic
entity tables); Crate Digger's start clean from `packages/db/init.sql` and
add additive changes via numbered files in `packages/db/migrations/`.

The `current_setting('app.current_user_id')` RLS pattern is set up here so
per-request handlers can `SET LOCAL` it for queries against feedback /
annotations / taste_profiles.
"""
from __future__ import annotations

import asyncpg

from app.config import settings

_pool: asyncpg.Pool | None = None


async def init_pool() -> None:
    global _pool
    _pool = await asyncpg.create_pool(
        settings.database_url,
        # Pool max=5 stays within Neon hobby/free connection cap (Sift convention).
        min_size=2,
        max_size=5,
    )
    await _apply_migrations(_pool)


async def _apply_migrations(pool: asyncpg.Pool) -> None:
    """Idempotent additive migrations run at startup.

    Uses IF NOT EXISTS / DO $$ guards so repeat deploys are no-ops. Operator
    versions (with CONCURRENTLY where applicable) live in the numbered SQL
    files under packages/db/migrations/ for manual application against
    live production DBs.

    Empty for now — fresh DBs initialize from packages/db/init.sql via
    docker-compose's docker-entrypoint-initdb.d. Add future schema changes
    here as they're generated by `pnpm db:generate`.
    """
    async with pool.acquire() as _conn:
        # Future migrations land here. Each block should be:
        #   await conn.execute("CREATE INDEX IF NOT EXISTS ...")
        #   await conn.execute("ALTER TABLE ... ADD COLUMN IF NOT EXISTS ...")
        # See HARVESTED_FROM_SIFT.md for the convention rationale.
        pass


async def get_pool() -> asyncpg.Pool:
    if _pool is None:
        raise RuntimeError("Database pool not initialized. Call init_pool() first.")
    return _pool


async def close_pool() -> None:
    global _pool
    if _pool:
        await _pool.close()
        _pool = None
